name: example_get_clean
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0-87.0.dev <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  retrofit: ^4.0.3
  dio: ^5.4.0
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  pretty_dio_logger: ^1.3.1
  get_storage: ^2.1.1
  json_annotation: ^4.8.1
  flutter_easyloading: ^3.0.5
  socket_io_client: ^2.0.3+1
  path_provider: ^2.1.1
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter

flutter: 
  uses-material-design: true

